services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - EXPIRE_JWT_AUTH=${EXPIRE_JWT_AUTH}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_FAILED_CALLBACK_URL=${GOOGLE_FAILED_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - '3000:3000'
    networks:
      - todo-app-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-app-network
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
